name: Cache workflow test

on: [push]

jobs:
  cache-hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check cached all files
        id: cache-all
        uses: actions/cache@v1
        with:
          path: tests
          key: ${{ runner.os }}-${{ hashFiles('**/*') }}

      - name: Check cached all files 2
        id: cache-all-2
        uses: actions/cache@v1
        with:
          path: tests
          key: ${{ runner.os }}-${{ hashFiles('**/**') }}

      - name: Check cached test folder
        id: cache-tests
        uses: actions/cache@v1
        with:
          path: tests
          key: ${{ runner.os }}-${{ hashFiles('tests/**/*') }}

      - name: Check cached workflow file
        id: cache-this-file
        uses: actions/cache@v1
        with:
          path: tests
          key: ${{ runner.os }}-${{ hashFiles('.github/workflows/cache-hash.yml') }}



 # changed
