name: Cache workflow test

on: [push]

jobs:
  writeAndCheckOnPath:
    runs-on: ubuntu-latest
    container:
      image: node:10.16-jessie
      volumes:
        - /my_volume
    steps:
     - run: |
        pwd
        ls $path/ -la
        touch $path/myFile.txt
        ls $path/ -la
        echo "Hello World!" > $path/myFile.txt
        cat $path/myFile.txt
       env:
         path: "/my_volume"

  readOnPath:
    runs-on: ubuntu-latest
    container:
      image: node:10.16-jessie
      volumes:
        - /my_volume
    needs: writeAndCheckOnPath
    steps:
     - run: |
        pwd
        ls $path/ -la
        cat $path/myFile.txt
       env:
         path: "/my_volume"
