name: Mac .app file download test
on: push

jobs:
  download_mac_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Download .app file
        run: |
          wget --recursive --cut-dirs=2 --no-host-directories https://app-deployment.meetbreakout.com/dependences/OBS.app

      - name: List files
        run: ls -la

      - name: List files on app
        run: cd OBS.app && ls -la
