version: '3'

services:
  web:
    container_name: backend
    build: .
    volumes:
      - ~/app_name:/code
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
pgdata: