name: Cache workflow test

on: [push]

jobs:
  writeAndCheckOnPath:
    runs-on: ubuntu-latest
    steps:
     - run: |
        pwd
        ls $path/ -la
        touch $path/myFile.txt
        ls $path/ -la
        echo "Hello World!" > $path/myFile.txt
        cat $path/myFile.txt
       env:
         path: "."

  readOnPath:
    runs-on: ubuntu-latest
    steps:
     - run: |
        pwd
        ls $path/ -la
        cat $path/myFile.txt
       env:
         path: "."
