name: Cache workflow test

on: [push]

jobs:
  writeHere:
    runs-on: ubuntu-latest
    steps:
     - run: |
        pwd
        ls
        touch myFile.txt
        ls
        echo "A test ok" > myFile.txt
        cat myFile.txt

  write:
    runs-on: ubuntu-latest
    steps:
     - run: |
        pwd
        touch /github/workspace/myFile.txt
        echo "A test ok" > /github/workspace/myFile.txt

  read:
    runs-on: ubuntu-latest
    steps:
     - run: cat /github/workspace/myFile.txt
