name: My Workflow with multiple commands

on: [push]

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          echo "A message"
          npm install
          echo "Another message or command"
          ./some-shell-script-file.sh
          bash some-shell-script-file.sh -x
      - run: echo One last message
