name: Secret test

on: [push]

jobs:
  validateSecret:
    runs-on: ubuntu-latest
    with:
      MY_SECRET
    steps:
     - run: |
        echo $MY_SECRET

  validateSecretEnv:
    runs-on: ubuntu-latest
    with:
      MY_SECRET
    env:
      MY_SECRET
    steps:
     - run: |
        echo $MY_SECRET
